#ifndef __LINUX_COALAPAGING_STATS_H
#define __LINUX_COALAPAGING_STATS_H

/* procfs stats */
#define GENERATE_ENUM(ENUM) ENUM,
#define GENERATE_STR(STR) #STR,

#define CONTIG_FAILURES(WRAP) \
	WRAP(INVALID_PFN) \
	WRAP(EXCEED_MEMORY) \
	WRAP(GUARD_PAGE) \
	WRAP(OCCUPIED) \
	WRAP(BUDDY_OCCUPIED) \
	WRAP(WRONG_ALIGNMENT) \
	WRAP(EXCEED_ZONE) \
	WRAP(NOTHING_FOUND) \
	WRAP(BUDDY_GUARD) \
	WRAP(SUBBLOCK_F) \
	WRAP(PAGECACHE_F) \
	WRAP(NUMA_F) \
	WRAP(SLAB) \
	WRAP(PCP_F) \
	WRAP(SPLIT) \
	WRAP(CONTPTE_F) \
	WRAP(CONTPMD_F) \
	WRAP(NUM_CONTIG_FAILURES) \

enum contig_failures_enum {
	CONTIG_FAILURES(GENERATE_ENUM)
};

#define CONTIG_SUCCESS(WRAP) \
	WRAP(SUPERBLOCK) \
	WRAP(SUBBLOCK_S) \
	WRAP(EXACT) \
	WRAP(RMM_RESERVED) \
	WRAP(PAGECACHE) \
	WRAP(PCP) \
	WRAP(CONTPTE) \
	WRAP(CONTPMD) \
	WRAP(NUM_CONTIG_SUCCESS) \

enum contig_success_enum {
	CONTIG_SUCCESS(GENERATE_ENUM)
};

#define FAIL_STAT(WRAP) \
	WRAP(ANON_SAME_PROCESS_SAME_VMA) \
	WRAP(ANON_SAME_PROCESS_DIFFERENT_VMA) \
	WRAP(ANON_OTHER_PROCESS) \
	WRAP(NOT_ANON) \
	WRAP(NUM_FAIL_STAT) \

enum fail_stat_enum {
	FAIL_STAT(GENERATE_ENUM)
};

#define PAGEHINT_STAT(WRAP) \
	WRAP(PAGEHINT_CONTPTE) \
	WRAP(PAGEHINT_PMD) \
	WRAP(PAGEHINT_CONTPMD) \
	WRAP(PAGEHINT_NONE_THPCHECK) \
	WRAP(PAGEHINT_NONE) \
	WRAP(PAGEHINT_NONE_FALLBACK) \
	WRAP(PAGEHINT_CONTPMD_ALLOC) \
	WRAP(PAGEHINT_CONTPMD_ALLOC_F) \
	WRAP(PAGEHINT_CONTPMD_ALLOC_R) \
	WRAP(PAGEHINT_CONTPMD_SKIPPED) \
	WRAP(PAGEHINT_OVERSIZED) \
	WRAP(PAGEHINT_OOB) \
	WRAP(PAGEHINT_HINT_MISMATCH) \
	WRAP(NUM_PAGEHINT_STAT) \

enum pagehint_stat_enum {
	PAGEHINT_STAT(GENERATE_ENUM)
};

extern atomic64_t contiguity_failure[MAX_ORDER][NUM_CONTIG_FAILURES];
extern atomic64_t contiguity_success[MAX_ORDER][NUM_CONTIG_SUCCESS];

extern atomic64_t total_contiguity_failure[NUM_CONTIG_FAILURES];
extern atomic64_t total_contiguity_success[NUM_CONTIG_SUCCESS];

extern atomic64_t total_alloc_hint;
extern atomic64_t pagehint_stats[NUM_PAGEHINT_STAT];

extern atomic64_t migrated_pages;
extern atomic64_t contpmd_compact_success;
extern atomic64_t contpmd_compact_fail;

#endif /* LINUX_COALAPAGING_STATS_H*/
